<pre class='metadata'>
Title: Deduced return types for defaulted operator functions
Shortname: D2952
Revision: 3
!Draft Revision: 17
Audience: CWG
Status: D
Group: WG21
URL:
Editor: Arthur O'Dwyer, arthur.j.odwyer@gmail.com
Editor: Matthew Taylor, mjtaylor214@hotmail.com
Markup Shorthands: markdown yes, biblio yes, markup yes
Abstract:
  Current C++ forbids explicitly defaulted functions to have placeholder return types such as <code>auto&</code>,
  except for C++20's <code>operator&lt;=&gt;</code>. We remove this syntactic restriction
  in cases where the deduced return type would be the same as the expected one.
  This allows more consistency and less repetition when declaring defaulted functions.
Date: 2026-09-17
</pre>

<style>
p    {-moz-hyphens: none; -ms-hyphens: none; -webkit-hyphens: none; hyphens: none;}
ins  {background-color: #CCFFCC; text-decoration: underline;}
del  {background-color: #FFCACA; text-decoration: line-through;}
</style>

# Changelog # {#changelog}

- R3 (pre-Búzios):

    - Wording changes after CWG review.

    - Change paper title to be more descriptive of the full scope of the paper.

    - Update divergence table in [[#corner-cases]]; list compiler versions tested.

- R2 (pre-Hagenberg):

    - Forward to CWG (see [[#polls]]).

    - Fix one mistake in a drafting note ("deleted" to "ill-formed").

- R1:

    - Add discussion of `void operator=(X&&) = default`, and of triviality, in [[#other-return-types]].


# Motivation # {#motivation}

Current C++ permits `=default` to appear only on certain signatures, with certain return types.
The current wording prohibits the use of placeholder types such as `auto&` to express these return
types, with the single exception of C++20's `operator<=>`. This leads to redundant repetition,
such as in this real code from libc++'s test suite:

<table>
<tr><th>Today</th><th>After P2952</th></tr>
<tr><td>
<small><pre>
struct ForwardDiffView {
  [...]
  ForwardDiffView(ForwardDiffView&&) = default;
  ForwardDiffView(const ForwardDiffView&) = default;
  ForwardDiffView& operator=(ForwardDiffView&&) = default;
  ForwardDiffView& operator=(const ForwardDiffView&) = default;
  [...]
};
</pre></small>
</td><td>
<small><pre>
struct ForwardDiffView {
  [...]
  ForwardDiffView(ForwardDiffView&&) = default;
  ForwardDiffView(const ForwardDiffView&) = default;
  auto& operator=(ForwardDiffView&&) = default;
  auto& operator=(const ForwardDiffView&) = default;
  [...]
};
</pre></small>
</td></tr>
</table>

The comparison operators are inconsistent among themselves: `operator<=>`
can deduce `strong_ordering`, but the others cannot deduce `bool`.

<table>
<tr><th>Today</th><th>After P2952</th></tr>
<tr><td>
<small><pre>
auto operator<=>(const MyClass& rhs) const = default;
bool operator==(const MyClass& rhs) const = default;
bool operator<(const MyClass& rhs) const = default;
</pre></small>
</td><td>
<small><pre>
auto operator<=>(const MyClass& rhs) const = default;
auto operator==(const MyClass& rhs) const = default;
auto operator<(const MyClass& rhs) const = default;
</pre></small>
</td></tr>
</table>

The status quo is inconsistent between non-defaulted and defaulted functions,
making it unnecessarily tedious to upgrade to `=default`:

<table>
<tr><th>Today</th><th>After P2952</th></tr>
<tr><td>
<pre><small>
<del>auto</del>& operator=(const MyClass& r) <del>{ i = r.i; return *this; }</del>
<ins>MyClass</ins>& operator=(const MyClass& r) <ins>= default;</ins>
</small></pre>
</td><td>
<pre><small>
auto& operator=(const MyClass& r) <del>{ i = r.i; return *this; }</del>
auto& operator=(const MyClass& r) <ins>= default;</ins>
</small></pre>
</td></tr>
<tr><td>
<pre><small>
<del>auto</del> operator==(const MyClass& r) const <del>{ return i == r.i; }</del>
<ins>bool</ins> operator==(const MyClass& r) const <ins>= default;</ins>
</small></pre>
</td><td>
<pre><small>
auto operator==(const MyClass& r) const <del>{ return i == r.i; }</del>
auto operator==(const MyClass& r) const <ins>= default;</ins>
</small></pre>
</td></tr>
</table>

The ill-formedness of these declarations comes from overly restrictive wording in the standard,
such as <a href="https://eel.is/c++draft/class.eq#1.sentence-1">[class.eq]/1</a>
specifically requiring that a defaulted equality
operator must have a *declared* return type of `bool`, instead of simply specifying that its return type
must *be* `bool`.
We believe each of the examples above has an intuitively clear meaning: the placeholder return type
correctly matches the type which the defaulted body will actually return. We propose to loosen the
current restrictions and permit these declarations to be well-formed.

This proposal does not seek to change the set of valid return types for these functions.
We propose a purely syntactic change to expand the range of allowed declaration *syntax*, not semantics.
(But we do one drive-by clarification which we believe matches EWG's original intent:
if an empty class's defaulted `operator<=>` returns a non-comparison-category type,
it should be defaulted as deleted.)

# Proposal # {#proposal}

We propose that a defaulted function declaration with a placeholder return type should have its
type deduced (<a href="https://eel.is/c++draft/dcl.spec.auto.general#3.sentence-4">[dcl.spec.auto.general]</a>)
as if from a fictional return statement that returns:

* a prvalue of type `bool`, in the case of `operator==`, `operator!=`, `operator<`, `operator>`, `operator<=`, or `operator>=`
* a prvalue of type `Q`, in the case of `operator<=>`; where `Q` is the common comparison type of <i>R</i><sub>0</sub>, <i>R</i><sub>1</sub>,... <i>R</i><sub>n-1</sub>
* an lvalue of type `C`, in the case of `operator=` for a class type `C`
* an lvalue of type `C`, in the case of `operator++` or `operator--` for a class type `C`

Then, the deduced return type is compared to the return type(s) permitted by the standard.
If the types match, the declaration is well-formed. Otherwise it's ill-formed.

<div class="example">
For the copy-assignment operator, our proposal gives the following behavior:

```cpp
struct MyClass {
  auto& operator=(const MyClass&) = default;          // Proposed OK: deduces MyClass&
  decltype(auto) operator=(const MyClass&) = default; // Proposed OK: deduces MyClass&
  auto&& operator=(const MyClass&) = default;         // Proposed OK: deduces MyClass&
  const auto& operator=(const MyClass&) = default;    // Still ill-formed: deduced const MyClass& is not MyClass&
  auto operator=(const MyClass&) = default;           // Still ill-formed: deduced MyClass is not MyClass&
  auto* operator=(const MyClass&) = default;          // Still ill-formed: deduction fails
  void operator=(const MyClass&) = default;           // Still ill-formed: void is not MyClass&
};
```

For `operator==`, our proposal gives the following behavior:

```cpp
struct MyClass {
  auto operator==(const MyClass&) const = default;           // Proposed OK: deduces bool
  decltype(auto) operator==(const MyClass&) const = default; // Proposed OK: deduces bool
  auto&& operator==(const MyClass&) const = default;         // Still ill-formed: deduced bool&& is not bool
  auto& operator==(const MyClass&) const = default;          // Still ill-formed: deduction fails
};
```
</div>

## "Return type" versus "declared return type" ## {#declared-type}

Today, vendors unanimously reject `auto& operator=(const A&) = default`.
But we can't find any wording in <a href="https://eel.is/c++draft/class.copy.assign">[class.copy.assign]</a>
or <a href="https://eel.is/c++draft/dcl.fct.def.default">[dcl.fct.def.default]</a> that directly justifies
this behavior. It seems that vendors are interpreting e.g. <a href="https://eel.is/c++draft/dcl.fct.def.default#2.5">[dcl.fct.def.default]/2.5</a>'s
"[if] the return type of F<sub>1</sub> differs from the return type of F<sub>2</sub>"
to mean "the *declared* return type of F<sub>1</sub>," even though newer sections such as
<a href="https://eel.is/c++draft/class.compare">[class.compare]</a> consistently distinguish
the "declared return type" from the (actual) return type.

We tentatively propose to leave <a href="https://eel.is/c++draft/dcl.fct.def.default">[dcl.fct.def.default]</a> alone,
and simply add an example that indicates the (new) intent of the (existing) wording: that it should
now be interpreted as talking about the assignment operator's *actual* return type,
not its *declared* (placeholder) return type.


## "Defaulted as deleted" ## {#defaulted-as-deleted}

The current wording for comparison operators is crafted so that the following `Container` is well-formed.
Its `operator<=>` is defaulted as deleted (so that operator is unusable), but the instantiation
of class `Container<mutex>` itself is OK. We need to preserve this in our rewriting.
([Godbolt.](https://godbolt.org/z/jcPf1Ge9W))
```cpp
template<class T>
struct Container {
  T t;
  auto operator<=>(const Container&) const = default;
};

Container<std::mutex> cm;
  // OK, <=> is deleted

struct Weird { int operator<=>(Weird) const; };
Container<Weird> cw;
  // OK, <=> is deleted because Weird's operator<=>
  // returns a non-comparison-category type
```

Similarly for dependent return types:
```cpp
template<class R>
struct C {
  int i;
  R operator<=>(const C&) const = default;
};
static_assert(std::three_way_comparable<C<std::strong_ordering>>);
static_assert(!std::three_way_comparable<C<int>>);
  // OK, C<int>'s operator<=> is deleted
```

Therefore we can't just say "`operator<=>` *shall* have a return type which is a comparison category type";
we must say that if the return type is not a comparison category type then the operator is defaulted as deleted.

## "Deducing `this`" and CWG2586 ## {#deducing-this}

[[CWG2586]] (adopted for C++23) permits defaulted functions to have explicit object parameters.
This constrains the wordings we can choose for `operator=`: we can't say “the return type is deduced
as if from `return *this`” because there might not be a `*this`.

There's a quirk with rvalue-ref-qualified assignment operators — not *move* assignment, but
assignment where the *destination* object is explicitly rvalue-ref-qualified.

* `auto&& operator=(const B&) && { return *this; }` deduces an lvalue reference
* `auto&& operator=(this B&& self, const B&) { return self; }` deduces an rvalue reference

Nonetheless, a *defaulted* assignment operator always returns an lvalue reference
(<a href="https://eel.is/c++draft/class.copy.assign#6.sentence-1">[class.copy.assign]/6</a>,
<a href="https://eel.is/c++draft/dcl.fct.def.default#2.5">[dcl.fct.def.default]/2.5</a>),
regardless of whether it's declared using explicit object syntax.

```cpp
struct A {
  A& operator=(const A&) && = default; // OK today
  A&& operator=(const A&) && = default; // Ill-formed, return type isn't A&
  decltype(auto) operator=(const A&) && { return *this; } // OK, deduces A&
  decltype(auto) operator=(const A&) && = default; // Ill-formed since P2953; would have deduced A&
};
struct B {
  B& operator=(this B&& self, const B&) { return self; } // Error, self can't bind to B&
  B&& operator=(this B&& self, const B&) { return self; } // OK
  decltype(auto) operator=(this B&& self, const B&) { return self; } // OK, deduces B&&
  B& operator=(this B& self, const B&) = default; // OK
  B& operator=(this B&& self, const B&) = default; // OK
  B&& operator=(this B&& self, const B&) = default; // Ill-formed, return type isn't B&
  decltype(auto) operator=(this B&& self, const B&) = default; // Proposed OK, deduces B&
};
```

Defaulted rvalue-ref-qualified assignment operators are weird; C++29 has adopted our [[P2953]]
which forbids them entirely. Either way, P2952 doesn't need to treat them specially.
Defaulted assignment operators invariably return lvalue references, so we invariably deduce as-if-from
an lvalue reference, full stop.

See [[#polls]].

## Burden on specifying new defaultable operators ## {#new-burden}

We propose to leave <a href="https://eel.is/c++draft/dcl.fct.def.default">[dcl.fct.def.default]</a> alone
and reinterpret its term "return type" to mean the actual return type, not the declared return type.
This will, by default, permit the programmer to use placeholder return types on their defaulted operators.
So there is a new burden on the specification of the defaultable operator, to specify exactly how
return type deduction works for the implicitly defined operator.

<div class="example">
[[P3668]], adopted for C++29, made postfix `operator++(int)` defaultable in
the same way as a secondary comparison operator, by
adding wording to <a href="https://eel.is/c++draft/over.oper#over.inc">[over.inc]</a>.
P2952 needs to modify this wording (see [[#wording-over.inc.default]] below)
to specify exactly how return type deduction works for defaulted increment and decrement operators.
</div>
 
## Other return types are still forbidden ## {#other-return-types}

Notice that returning any type other than `X&` from a defaulted `X::operator=` remains ill-formed.
For example, we don't propose to accept:
```cpp
struct X {
  void operator=(X&&) = default; // still ill-formed
};
```
Any paper that did propose to permit defaulting `void operator=` would have to consider very carefully
whether to call that operator "trivial." Today,
`is_trivially_move_assignable_v<T>` is true only when
`decltype(declval<T&>() = declval<T>())` is `T&`. It's just barely conceivable that existing
user code *might* rely on that fact, and break when presented with a trivial assignment
operator that returned `void` instead. And certainly the return-by-copy `X operator=(X&&) = default`
shouldn't be considered "trivial" for non-trivially-copy-constructible `X`.

But none of this is a problem for this proposal P2952, because we propose to continue rejecting
a defaulted `X::operator=` that returns any type but `X&`. We merely propose to allow the programmer
to *spell* that return type using a placeholder such as `auto&`.

## Existing corner cases ## {#corner-cases}

There is vendor divergence in some corner cases. Here is a table of the divergences we found,
plus our opinion as to the conforming behavior, and our proposed behavior. The compilers tested are
GCC 16, Clang 23, MSVS 18.6, and EDG 6.9.

<small><table>
<tr><th>URL</th><th>Code</th><th>GCC</th><th>Clang</th><th>MSVC</th><th>EDG</th><th>Correct</th></tr>
<tr><td><a href="https://godbolt.org/z/5jGoMedsY">link</a></td><td><pre>const bool operator==(const C&) const = default;</pre></td>
    <td>✗</td><td>✗</td><td>✗</td><td bgcolor="#FFCACA">✓</td><td><a href="https://eel.is/c++draft/class.eq#1.sentence-1">✗</a></td></tr>
<tr><td><a href="https://godbolt.org/z/sKGM6Ecja">link</a></td><td><pre>friend bool operator==(const C, const C) = default;</pre></td>
    <td>✓</td><td bgcolor="#FFCACA">✗</td><td>✓</td><td>✓</td><td><a href="https://eel.is/c++draft/class.compare#default-1.sentence-1">✓</a></td></tr>
<tr><td><a href="https://godbolt.org/z/1a6e6aTre">link</a></td><td><pre>decltype(auto) operator<=>(const C&) const = default;</pre></td>
    <td bgcolor="#FFCACA">✓</td><td>✗</td><td>✗</td><td>✗</td><td>Today: <a href="https://eel.is/c++draft/class.compare#class.spaceship-2.2.sentence-1">✗</a><br>Proposed: ✓</td></tr>
<tr><td><a href="https://godbolt.org/z/9q6rqGKKe">link</a></td><td><pre>const auto operator<=>(const C&) const = default;</pre></td>
    <td>✗</td><td>✗</td><td bgcolor="#FFCACA">✓</td><td bgcolor="#FFCACA">✓</td><td>Today: <a href="https://eel.is/c++draft/class.compare#class.spaceship-2.2.sentence-1">✗</a><br>Proposed: ✗</td></tr>
<tr><td><a href="https://godbolt.org/z/Pq7b9EEEh">link</a></td><td><pre>True auto operator<=>(const C&) const = default;</pre></td>
    <td bgcolor="#FFCACA">✓</td><td>✗</td><td bgcolor="#FFCACA">✓</td><td bgcolor="#FFCACA">✓</td><td>Today: <a href="https://eel.is/c++draft/class.compare#class.spaceship-2.2.sentence-1">✗</a><br>Proposed: ✓</td></tr>
<tr><td><a href="https://godbolt.org/z/oc8vxPsjn">link</a></td><td><pre>False auto operator<=>(const C&) const = default;</pre></td>
    <td bgcolor="#FFCACA">unmet</td><td>✗</td><td bgcolor="#FFCACA">✓</td><td bgcolor="#FFCACA">✓</td><td>Today: <a href="https://eel.is/c++draft/class.compare#class.spaceship-2.2.sentence-1">✗</a><br>Proposed: unmet</td></tr>
<tr><td><a href="https://godbolt.org/z/6b9cavdfs">link</a></td><td><pre>struct U { U(std::strong_ordering); };
struct C {
  U operator<=>(const C&) const = default;
};</pre></td>
    <td>✓</td><td>✓</td><td bgcolor="#FFCACA">✗</td><td bgcolor="#FFCACA">deleted</td><td>Today: ✓<br>Proposed: deleted</td></tr>
<tr><td><a href="https://godbolt.org/z/M7fvssjsM">link</a></td><td><pre>struct U { U(std::strong_ordering); operator int(); };
struct C {
  int i;
  U operator<=>(const C&) const = default;
};</pre></td>
    <td bgcolor="#FFCACA">✓</td><td bgcolor="#FFCACA">✓</td><td bgcolor="#FFCACA">✗</td><td>deleted</td><td><a href="https://eel.is/c++draft/class.compare#class.spaceship-2.2.sentence-2">deleted</a></td></tr>
<tr><td><a href="https://godbolt.org/z/Ka6Tbb1vq">link</a></td><td><pre>struct C {
  int i;
  const std::strong_ordering&
    operator<=>(const C&) const = default;
};</pre></td>
    <td bgcolor="#FFCACA"><a href="https://gcc.gnu.org/bugzilla/show_bug.cgi?id=127456">ICE</a></td><td bgcolor="#FFCACA">✓</td><td bgcolor="#FFCACA">✓</td><td>deleted</td><td>deleted</td></tr>
<tr><td><a href="https://godbolt.org/z/WYW7Tsre1">link</a></td><td><pre>struct C {
  const std::strong_ordering&
    operator<=>(const C&) const = default;
};</pre></td>
    <td>✓</td><td>✓</td><td>✓</td><td bgcolor="#FFCACA">deleted</td><td>Today: ✓<br>Proposed: deleted</td></tr>
<tr><td><a href="https://godbolt.org/z/q5WajKsr3">link</a><td><pre>auto operator<=>(const M&) const
  noexcept(false) = default;</pre></td>
    <td>✓</td><td>✓</td><td bgcolor="#FFCACA">noexcept</td><td bgcolor="#FFCACA">incon-<br>sistent</td><td><a href="https://eel.is/c++draft/class.compare#default-note-1">✓</a></td>
<tr><td><a href="https://godbolt.org/z/G14P6rd8v">link</a></td><td><pre>C& operator=(C&) = default;</pre></td>
    <td>✓</td><td>✓</td><td>✓</td><td>✓</td><td>✓</td></tr>
<tr><td><a href="https://godbolt.org/z/KEr81vanf">link</a></td><td><pre>C& operator=(const C&&) = default;</pre></td>
    <td>deleted</td><td>deleted</td><td bgcolor="#FFCACA">✗</td><td>deleted</td><td><a href="https://eel.is/c++draft/dcl.fct.def.default#2.6">deleted</a></td></tr>
<tr><td><a href="https://godbolt.org/z/6Y1f4ce9q">link</a></td><td><pre>C& operator=(const C&) const = default;</pre></td>
    <td>deleted</td><td>deleted</td><td bgcolor="#FFCACA">✓</td><td>deleted</td><td><a href="https://eel.is/c++draft/dcl.fct.def.default#2.6">deleted</a></td></tr>
<tr><td><a href="https://godbolt.org/z/bW893rjba">link</a></td><td><pre>C& operator=(const C&) && = default;</pre></td>
    <td bgcolor="#FFCACA">✓</td><td bgcolor="#FFCACA">✓</td><td bgcolor="#FFCACA">✓</td><td bgcolor="#FFCACA">✓</td><td><a href="https://eel.is/c++draft/dcl.fct.def.default#2.1">✗</a><br>only since [[P2953]]</td></tr>
<tr><td><a href="https://godbolt.org/z/boWPETYYd">link</a></td><td><pre>C&& operator=(const C&) && = default;</pre></td>
    <td>✗</td><td>✗</td><td>✗</td><td>✗</td><td><a href="https://eel.is/c++draft/dcl.fct.def.default#2.5">✗</a></td></tr>
</table></small>

## Impact on existing code ## {#impact}

There should be little effect on existing code, since this proposal mainly allows syntax that was ill-formed before.
As shown in [[#corner-cases]], we do propose to change some very arcane examples, e.g.
```cpp
struct C {
  const std::strong_ordering&
    operator<=>(const C&) const = default;
    // Today: Well-formed, non-deleted
    // Tomorrow: Well-formed, deleted
};
```

# Implementation experience # {#experience}

None yet.

# Straw poll results # {#polls}

Arthur O'Dwyer presented P2952R1 in the EWG telecon of 2025-01-08. The following straw polls were taken.
The first was interpreted as "no consensus"; the second was interpreted as consensus (pending electronic polling).

<table class="def">
<tr><th style="width: 70%;"></th><th>**SF**</th><th>**F**</th><th>**N**</th><th>**A**</th><th>**SA**</th></tr>

<tr><th><small>EWG prefers this paper contains the change in P2953
<br>(banning explicitly defaulted operator= with rvalue ref-qualifier).
<br>[Chair: This means EWG wants to see this paper again.]</small></th>
<th> 2 </th><th> 4 </th><th> 9 </th><th> 1 </th><th> 0 </th></tr>

<tr><th><small>Forward P2952R1 to CWG for inclusion in C++26, pending online polling.</small></th>
<th> 3 </th><th> 10 </th><th> 4 </th><th> 1 </th><th> 0 </th></tr>
</table>

The electronic poll <a href="https://wiki.isocpp.org/2025-02_Hagenberg:EWG-electronic-polling-P3310R5-and-P2952R1">was taken</a> as follows:

<table class="def">
<tr><th style="width: 70%;"></th><th>**SF**</th><th>**F**</th><th>**N**</th><th>**A**</th><th>**SA**</th></tr>
<tr><th><small>Forward P2952R1 to CWG for C++26 (pending confirmation during in-person meeting).</small></th>
<th> 3 </th><th> 6 </th><th> 1 </th><th> 1 </th><th> 0 </th></tr>
</table>

This paper was presented again to EWG in Hagenberg.
The following poll <a href="https://wiki.isocpp.org/2025-02_Hagenberg:NotesEWGP2952">was taken</a>:

<table class="def">
<tr><th style="width: 70%;"></th><th>**SF**</th><th>**F**</th><th>**N**</th><th>**A**</th><th>**SA**</th></tr>

<tr><th><small>P2952R2 auto& operator=(X&&) = default: forward to CWG for C++26.</small></th>
<th> 5 </th><th> 25  </th><th> 13 </th><th> 5 </th><th> 4 </th></tr>
</table>


# Proposed wording # {#wording}

## [class.eq] ## {#wording-class.eq}

<p class="note"><b>DRAFTING NOTE:</b>
The phrase "equality operator function" (<a href="https://eel.is/c++draft/over.binary">[over.binary]</a>)
means `==` or `!=`. But `!=` is not covered by [class.eq]; it's covered by [class.compare.secondary] below.

<p>Modify <a href="https://eel.is/c++draft/class.eq">[class.eq]</a> as follows:</p>

<small><blockquote>
<p>1․ A defaulted <del>equality</del> <ins>`==`</ins> operator function ([over.binary]) shall have <del>a declared</del> <ins>the</ins> return type `bool`.
<ins>If its declared return type contains a placeholder type, its return type is deduced as if from `return true;`.</ins>

<p>2․ A defaulted `==` operator function for a class `C` is defined as deleted unless, for each `x`<sub><i>i</i></sub>
in the expanded list of subobjects for an object `x` of type `C`, `x`<sub><i>i</i></sub> `== x`<sub><i>i</i></sub> is usable
([class.compare.default]).

<p>3․ The return value of a defaulted `==` operator function with parameters `x` and `y` is determined by comparing corresponding elements
`x`<sub><i>i</i></sub> and `y`<sub><i>i</i></sub> in the expanded lists of subobjects for `x` and `y` (in increasing index order)
until the first index <i>i</i> where `x`<sub><i>i</i></sub> `==` `y`<sub><i>i</i></sub> <del>yields a result value
which</del> , <del>when</del> contextually converted to `bool`, yields `false`.
The return value is `false` if such an index exists and `true` otherwise.

<p>4․ [<i>Example 1:</i>
<pre>
struct D {
  int i;
  friend bool operator==(const D& x, const D& y) = default;
      // OK, returns x.i == y.i
};
</pre>
— <i>end example</i>]
</blockquote></small>

## [class.spaceship] ## {#wording-class.spaceship}

<p class="note"><b>DRAFTING NOTE:</b>
There are only three "comparison category types" in C++, and `strong_ordering::equal` is implicitly convertible
to all three of them. The status quo already effectively forbids `<=>` to return a non-comparison-category type,
since either `R` is deduced as a common comparison type (which is a comparison category type by definition), or else
a synthesized three-way comparison of type `R` must exist (which means `R` must be a comparison category type),
or else the sequence `x`<sub><i>i</i></sub> must be empty (in which case there are no restrictions on `R` except
that it be constructible from `strong_ordering::equal`). We strengthen the wording to directly mandate that the
return type be a comparison category type, even in the empty case.

<p>Modify <a href="https://eel.is/c++draft/class.spaceship">[class.spaceship]</a> as follows:</p>

<small><blockquote>
<p>[...]

2․ Let `R` be the declared return type of a defaulted three-way comparison operator function, and let
`x`<sub><i>i</i></sub> be the elements of the expanded list of subobjects for an object `x` of type `C`.

— (2.1) If `R` <del>is `auto`</del> <ins>contains a placeholder type</ins>, then let
<i>cv<sub>i</sub></i> <del>`R`</del><ins>`S`</ins><sub><i>i</i></sub> be the type of the expression
`x`<sub><i>i</i></sub> `<=> x`<sub><i>i</i></sub>. The operator function is defined as deleted if that expression is not usable
or if <del>`R`</del><ins>`S`</ins><sub><i>i</i></sub> is not a comparison category type ([cmp.categories.pre]) for any <i>i</i>.
The return type is deduced as <ins>if from `return Q(std::strong_ordering::equal);` where `Q` is</ins> the common comparison type (see below) of <del>`R`</del><ins>`S`</ins><sub>0</sub>, <del>`R`</del><ins>`S`</ins><sub>1</sub>, ..., <del>`R`</del><ins>`S`</ins><sub>n-1</sub>.

— (2.2) Otherwise, <del>`R` shall not contain a placeholder type. If</del> <ins>if</ins> the synthesized three-way comparison of type `R`
between any objects `x`<sub><i>i</i></sub> and `x`<sub><i>i</i></sub> is not defined, the operator function is
defined as deleted.

<ins>x․ A defaulted three-way comparison operator function that is not defined as deleted shall have a return type which is a comparison category type
([cmp.categories.pre]).</ins>

3․ The return value of type `R` of the defaulted three-way comparison operator function with parameters `x` and `y` <del>of
the same type</del> is determined by comparing corresponding elements `x`<sub><i>i</i></sub> and `y`<sub><i>i</i></sub>
in the expanded lists of subobjects for `x` and `y` (in increasing index order) until the first index <i>i</i>
where the synthesized three-way comparison of type `R` between `x`<sub><i>i</i></sub> and `y`<sub><i>i</i></sub>
yields a result value `v`<sub><i>i</i></sub> where `v`<sub><i>i</i></sub> `!= 0`, contextually converted to `bool`,
yields `true`. The return value is <del>a copy of</del> `v`<sub><i>i</i></sub> if such an index exists
and `static_cast<R>(std::strong_ordering::equal)` otherwise.

4․ The <i>common comparison type</i> `U` of a possibly-empty list of <i>n</i> comparison category types
`T`<sub>0</sub>, `T`<sub>1</sub>, ..., `T`<sub>n-1</sub> is defined as follows: [...]
</blockquote></small>

## [class.compare.secondary] ## {#wording-class.compare.secondary}

Modify <a href="https://eel.is/c++draft/class.compare.secondary">[class.compare.secondary]</a> as follows:

<small><blockquote>
<p>1․ A <i>secondary comparison operator</i> <ins>`@`</ins> is a relational operator ([expr.rel]) or the `!=` operator. <del>A
defaulted operator function ([over.binary]) for a secondary comparison operator `@` shall have a declared return type `bool`.</del>

<p><ins>x․ A defaulted secondary comparison operator function shall have the return type `bool`. If its declared return type
contains a placeholder type, its return type is deduced as if from `return true;`.</ins>

2․ <del>The</del> <ins>A defaulted secondary comparison</ins> operator function with parameters `x` and `y` is defined as deleted if

— (2.1) a first overload resolution ([over.match]), as applied to `x @ y`,

— (2.1.1) does not result in a usable candidate, or

— (2.1.2) the selected candidate is not a rewritten candidate, or

— (2.2) a second overload resolution for the expression resulting from the interpretation
of `x @ y` using the selected rewritten candidate ([over.match.oper]) does not result
in a usable candidate (for example, that expression might be `(x <=> y) @ 0`), or

— (2.3) `x @ y` cannot be implicitly converted to `bool`.

In any of the two overload resolutions above, the defaulted operator function is
not considered as a candidate for the `@` operator. Otherwise, the operator function
yields `x @ y`.

3․ [<i>Example 1</i>:
<pre>
struct HasNoLessThan { };

struct C {
  friend HasNoLessThan operator<=>(const C&, const C&);
  bool operator<(const C&) const = default; // OK, function is deleted
};
</pre>
— <i>end example</i>]
</blockquote></small>

## [class.copy.assign] ## {#wording-class.copy.assign}

<p class="note"><b>DRAFTING NOTE:</b>
<a href="https://eel.is/c++draft/class.copy.assign#6.sentence-1">[class.copy.assign]/6</a>
already clearly states that "The implicitly-declared copy/move assignment operator for class `X` has the return type `X&`."
But we need this new wording to ensure that an *explicitly-defaulted* copy/move assignment operator
will deduce that same type. (If it deduces a different type, then the explicitly-defaulted operator
becomes ill-formed, as in example `B` below.)

<p>Modify <a href="https://eel.is/c++draft/class.copy.assign">[class.copy.assign]</a> as follows:</p>

<small><blockquote>
<p>14․ The implicitly-defined copy/move assignment operator for a class returns
the object for which the assignment operator is invoked, that is,
the object assigned to.

<p><ins>15․ If the declared return type of a defaulted copy/move assignment operator for a class `X` contains a
placeholder type, its return type is deduced as if from `return r;`, where `r` is an lvalue
reference to `X`.</ins>

<p><ins>16․ \[<i>Example:</i></ins>
<pre>
<ins>struct A {</ins>
  <ins>decltype(auto) operator=(A&&) = default;</ins>
    <ins><i>// OK, return type is A&</i></ins>
<ins>};</ins>
<ins>struct B {</ins>
  <ins>auto operator=(B&&) = default;</ins>
    <ins><i>// error: return type is B, which violates [dcl.fct.def.default]</i></ins>
<ins>};</ins>
</pre>
<ins>—<i>end example</i>]</ins>
</blockquote>
</small>

## [over.inc.default] ## {#wording-over.inc.default}

Modify <a href=https://eel.is/c++draft/over.inc.default>[over.inc.default]</a> as follows:

<small><blockquote>
<p>1․ A defaulted postfix increment or decrement operator function for a type `C` shall be a non-template function that
<p> — (1.1) has a first parameter of type “reference to `C`” or a first parameter of type “reference to volatile `C`”,
where the implicit object parameter (if any) is considered to be the first parameter,
<p> — (1.2) is defined as defaulted in `C` or in a context where `C` is complete, and
<p> — (1.3) has <del>a declared</del> <ins>the</ins> return type <del>of</del> `C`.

<p>[...]

<p>3․ The implicit definition of a defaulted postfix increment or decrement operator function `F`
that is not defined as deleted for a type `C` is equivalent to
<pre>
C <i>tmp</i>(c);
++c;
return <i>tmp</i>;
</pre>
for a postfix increment operator function, or
<pre>
C <i>tmp</i>(c);
--c;
return <i>tmp</i>;
</pre>
for a postfix decrement operator function,
where <i><code>tmp</code></i> is a variable defined for exposition only,
and `c` is an lvalue that denotes `*this` if `F` is an implicit object member function, or the first parameter of `F` otherwise.

<p><ins>x. If the declared return type of a defaulted postfix increment or decrement operator function
that is not defined as deleted contains a placeholder type,
its return type is deduced as if from <code>return <i>tmp</i>;</code>.</ins>

<p>4․ [<i>Example:</i> [...]
</blockquote></small>

## Annex C, [diff.cpp26] ## {#wording-annex-c}

Add a clause to Annex C, <a href="https://eel.is/c++draft/diff.cpp26">[diff.cpp26.class]</a>, as follows:

<blockquote>
<ins>
<b>Affected clause:</b> [class.spaceship]<br>
<b>Change:</b> A defaulted three-way comparison operator must return a comparison category type; otherwise, it is deleted.<br>
<b>Rationale:</b> The old behaviour was inconsistent and confusing. <br>
<b>Effect on original feature:</b> A valid C++26 program that contains a defaulted three-way comparison operator
with a return type that is not a comparison category type, and that attempts to call it, is ill-formed.<br>
<b>Example:</b></ins>
<pre>
<ins>struct C {</ins>
    <ins>const std::strong_ordering&amp; operator<=>(const C&amp;) const = default;</ins>
        <ins>// deleted; previously not deleted</ins>
<ins>};</ins>
</pre>
</blockquote>

<pre class=biblio>
{
  "CWG2586": {
    "title": "Explicit object parameter for assignment and comparison",
    "authors": [
      "Barry Revzin"
    ],
    "href": "https://cplusplus.github.io/CWG/issues/2586.html",
    "date": "May–July 2022"
  },
  "P0847": {
    "title": "Deducing this",
    "authors": [
      "Sy Brand",
      "Gašper Ažman",
      "Ben Deane",
      "Barry Revzin"
    ],
    "href": "https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2021/p0847r7.html",
    "date": "July 2021"
  },
  "P1046R2": {
    "title": "Automatically Generate More Operators",
    "authors": [
      "David Stone"
    ],
    "href": "https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2020/p1046r2.html",
    "date": "January 2020"
  },
  "P2953": {
    "title": "Adding restrictions to defaulted assignment operator functions",
    "authors": [
      "Matthew Taylor",
      "Arthur O'Dwyer"
    ],
    "href": "https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2026/p2953r5.html",
    "date": "June 2026"
  },
  "P3668": {
    "title": "Defaulting postfix increment and decrement operations",
    "authors": [
      "Matthew Taylor",
      "Alex (Waffl3x)"
    ],
    "href": "https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2026/p3668r4.html",
    "date": "June 2026"
  }
}
</pre>
